 

package GUI;

import NapakalakiGame.Cultist;
import NapakalakiGame.Treasure;
import java.awt.Color;

/**
 * @author Guillermo Muriel
 * @author Luis Liñán
 */
public class CultistView extends javax.swing.JPanel {

    Cultist cultistModel;
    boolean selected=false;
    Color color=Color.CYAN;

     public boolean isSelected() {
        return this.selected;
    }

    public Cultist getCultist() {
        return this.cultistModel;
    }
    /**
     * Creates new form TreasureView
     */
    public CultistView() {
        initComponents();
    }

    public void setCultist(Cultist c){
        cultistModel = c;
        nombre.setText(cultistModel.getName());
        gainedlevels.setText(Integer.toString(cultistModel.getGainedLevels()));
        /*if(isSelected()){
            this.setBackground(color);
        }*/
         this.setOpaque(this.isSelected());
        repaint();
        revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gainedlevels = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        min = new javax.swing.JLabel();

        setBackground(new java.awt.Color(62, 171, 208));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        gainedlevels.setText("gainedlevels");

        nombre.setText("Nombre");

        nom.setText("Nombre : ");

        min.setText("GainedLevels:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(min)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gainedlevels)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(202, 202, 202))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom)
                    .addComponent(nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(min)
                    .addComponent(gainedlevels))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if(this.isSelected()==true)
            selected=false;
        else
            selected=true;
        this.setOpaque(selected);
        repaint();
        revalidate();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gainedlevels;
    private javax.swing.JLabel min;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
