 
package GUI;
import NapakalakiGame.Napakalaki;
import NapakalakiGame.CombatResult;
import NapakalakiGame.Player;
/**
 * @author Guillermo Muriel
 * @author Luis Liñán
 */
public class NapakalakiView extends javax.swing.JFrame {
 Napakalaki napakalakiModel;
 Player playerModel;
 int cnt=0;
 boolean next_turn=true;
 boolean ganaste=false;
 boolean hacer_visible_comprar=false;
 boolean conocer=true;
 boolean lucha=true;
 boolean malrollo=false;
 
    public void setNapakalakiModel(Napakalaki napakalakiModel1) {
        this.napakalakiModel = napakalakiModel1;
        playerView.setNapakalakiView(this);
        playerModel=napakalakiModel.getCurrentPlayer();
        playerView.setNapakalaki(napakalakiModel);
        
        if(napakalakiModel.getResultado()==CombatResult.WinAndWinGame){
            ganaste=true;
            Next_turn.setEnabled(false);
            Combat.setEnabled(false);
            meet_the_monster.setEnabled(false);
        }else{
            Combat.setEnabled(!conocer);
            resultado.setVisible(!lucha);
            Next_turn.setEnabled(!lucha);
        }
        
        playerView.setPlayer(playerModel);
        monsterView.setMonster(napakalakiModel.getCurrentMonster());
        monsterView.setVisible(!conocer);
        HAS_GANADO.setVisible(ganaste);
        mal_rollo.setVisible(malrollo);
        resultado.setText(napakalakiModel.getResultado().name());
        repaint();
        revalidate();
    }
    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monsterView = new GUI.MonsterView();
        meet_the_monster = new javax.swing.JButton();
        Combat = new javax.swing.JButton();
        Next_turn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        mal_rollo = new javax.swing.JLabel();
        HAS_GANADO = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        playerView = new GUI.PlayerView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        meet_the_monster.setText("Meet the Monster");
        meet_the_monster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meet_the_monsterActionPerformed(evt);
            }
        });

        Combat.setText("Combat");
        Combat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombatActionPerformed(evt);
            }
        });

        Next_turn.setText("Next turn");
        Next_turn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_turnActionPerformed(evt);
            }
        });

        jLabel3.setText("Resultado");

        mal_rollo.setText("NOTA: No cumples el mal rollo o tienes 4 tesoros no visibles.");

        HAS_GANADO.setText("HAS GANADO!! ENHORABUENA!");

        resultado.setText("resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(meet_the_monster)
                        .addGap(191, 191, 191)
                        .addComponent(Next_turn)
                        .addGap(233, 233, 233)
                        .addComponent(Combat))
                    .addComponent(playerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monsterView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mal_rollo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HAS_GANADO, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(playerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(meet_the_monster)
                            .addComponent(Next_turn)
                            .addComponent(Combat)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(monsterView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HAS_GANADO, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mal_rollo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meet_the_monsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meet_the_monsterActionPerformed
        conocer=false;
        hacer_visible_comprar=true;
        setNapakalakiModel(napakalakiModel);
    }//GEN-LAST:event_meet_the_monsterActionPerformed

    private void CombatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombatActionPerformed
        if(cnt==0){
            napakalakiModel.developCombat();
            lucha=false;
            hacer_visible_comprar=false;
            cnt=cnt+1;
            setNapakalakiModel(napakalakiModel);
        }
    }//GEN-LAST:event_CombatActionPerformed

    private void Next_turnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_turnActionPerformed
        if(napakalakiModel.nextTurn()==true){
            cnt=0;
            next_turn=true;
            ganaste=false;
            hacer_visible_comprar=false;
            conocer=true;
            lucha=true;
            malrollo=false;
        }
        else{
            malrollo=true;
        }
        setNapakalakiModel(napakalakiModel);
    }//GEN-LAST:event_Next_turnActionPerformed

    public void showView() {
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Combat;
    private javax.swing.JLabel HAS_GANADO;
    private javax.swing.JButton Next_turn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel mal_rollo;
    private javax.swing.JButton meet_the_monster;
    private GUI.MonsterView monsterView;
    private GUI.PlayerView playerView;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
