 

package GUI;

import NapakalakiGame.Treasure;
import java.awt.Color;

/**
 * @author Guillermo Muriel
 * @author Luis Liñán
 */
public class TreasureView extends javax.swing.JPanel {

    Treasure treasureModel;
    boolean selected=false;
    Color color=Color.red;

    public boolean isSelected() {
        return this.selected;
    }

    public Treasure getTreasure() {
        return this.treasureModel;
    }
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }

    public void setTreasure (Treasure t) {
        treasureModel = t;
        nombre.setText(treasureModel.getName());
        maxBonus.setText(Integer.toString(treasureModel.getMaxBonus()));
        minBonus.setText(Integer.toString(treasureModel.getMinBonus()));
        oro.setText(Integer.toString(treasureModel.getGoldCoins()));
        tipo.setText(treasureModel.getType().toString());
        this.setOpaque(this.isSelected());
        repaint();
        revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelOro = new javax.swing.JLabel();
        minBonus = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        tip = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        maxBonus = new javax.swing.JLabel();
        oro = new javax.swing.JLabel();
        max = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        min = new javax.swing.JLabel();

        setBackground(new java.awt.Color(208, 62, 64));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        labelOro.setText("Oro : ");

        minBonus.setText("Min Bonus");

        tipo.setText("Tipo");

        tip.setText("Tipo : ");

        nombre.setText("Nombre");

        maxBonus.setText("Max Bonus");

        oro.setText("Oro");

        max.setText("Max Bonus :");

        nom.setText("Nombre : ");

        min.setText("Min Bonus : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(min)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minBonus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(max)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(maxBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelOro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom)
                    .addComponent(nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(min)
                    .addComponent(minBonus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxBonus)
                    .addComponent(max))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOro)
                    .addComponent(oro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tip)
                    .addComponent(tipo))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if(this.isSelected()==true)
            selected=false;
        else
            selected=true;
        this.setOpaque(selected);
        repaint();
        revalidate();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelOro;
    private javax.swing.JLabel max;
    private javax.swing.JLabel maxBonus;
    private javax.swing.JLabel min;
    private javax.swing.JLabel minBonus;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel oro;
    private javax.swing.JLabel tip;
    private javax.swing.JLabel tipo;
    // End of variables declaration//GEN-END:variables
}
